#############################################################################
# Makefile for building: smpcil
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  ./smpcil.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug Makefile ./smpcil.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CFLAGS        = -m64 -pipe -g -Wall -W -fPIC

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       =  ./smp_stl/smp_queue/smp_queue.c \
		./smp_stl/smp_tree/smp_rbt.c \
		./smp_mpool/smp_mpool.c \
		./smp_linux/smp_file/smp_file.c \
		./smp_linux/smp_error/smp_error.c \
		./smp_linux/smp_file/smp_sio.c \
		./smp_linux/smp_ipc/smp_sem.c \
		./smp_linux/smp_ipc/smp_msg.c \
		./smp_linux/smp_string/smp_string.c \
		./smp_linux/smp_string/smp_BoyerMoore.c \
		./smp_stl/smp_list/smp_list.c \
		./smp_stl/smp_stack/smp_stack.c \
		./smp_stl/smp_array/smp_array.c \
		./smp_stl/smp_link/smp_link.c \
		./smp_linux/smp_sig/smp_signal.c \
		./smp_linux/smp_system/smp_system.c 
OBJECTS       =  smp_queue.o \
		smp_rbt.o \
		smp_mpool.o \
		smp_file.o \
		smp_error.o \
		smp_sio.o \
		smp_sem.o \
		smp_msg.o \
		smp_string.o \
		smp_BoyerMoore.o \
		smp_list.o \
		smp_stack.o \
		smp_array.o \
		smp_link.o \
		smp_signal.o \
		smp_system.o 

####### Compile

libsmpcil.so: $(OBJECTS)
	$(CC)   -shared  -o libsmpcil.so $(OBJECTS)

smp_queue.o: ./smp_stl/smp_queue/smp_queue.c ./smpcil.h \
		./smp_linux/smp_error/smp_error.h \
		./smp_mpool/smp_mpool.h \
		./smp_stl/smp_queue/smp_queue.h \
		./smp_stl/smp_stl.h
	$(CC) -c $(CFLAGS)  -o smp_queue.o ./smp_stl/smp_queue/smp_queue.c

smp_rbt.o: ./smp_stl/smp_tree/smp_rbt.c ./smpcil.h \
		./smp_linux/smp_error/smp_error.h \
		./smp_stl/smp_queue/smp_queue.h \
		./smp_stl/smp_stl.h \
		./smp_mpool/smp_mpool.h \
		./smp_stl/smp_tree/smp_rbt.h
	$(CC) -c $(CFLAGS) -o smp_rbt.o ./smp_stl/smp_tree/smp_rbt.c

smp_mpool.o: ./smp_mpool/smp_mpool.c ./smpcil.h \
		./smp_linux/smp_error/smp_error.h \
		./smp_mpool/smp_mpool.h
	$(CC) -c $(CFLAGS) -o smp_mpool.o ./smp_mpool/smp_mpool.c

smp_file.o: ./smp_linux/smp_file/smp_file.c ./smpcil.h \
		./smp_linux/smp_file/smp_file.h \
		./smp_linux/smp_error/smp_error.h
	$(CC) -c $(CFLAGS) -o smp_file.o ./smp_linux/smp_file/smp_file.c

smp_error.o: ./smp_linux/smp_error/smp_error.c ./smpcil.h \
		./smp_linux/smp_error/smp_error.h
	$(CC) -c $(CFLAGS) -o smp_error.o ./smp_linux/smp_error/smp_error.c

smp_sio.o: ./smp_linux/smp_file/smp_sio.c ./smpcil.h \
		./smp_linux/smp_file/smp_file.h \
		./smp_linux/smp_error/smp_error.h
	$(CC) -c $(CFLAGS) -o smp_sio.o ./smp_linux/smp_file/smp_sio.c

smp_sem.o: ./smp_linux/smp_ipc/smp_sem.c ./smpcil.h \
		./smp_linux/smp_error/smp_error.h \
		./smp_linux/smp_ipc/smp_ipc.h
	$(CC) -c $(CFLAGS) -o smp_sem.o ./smp_linux/smp_ipc/smp_sem.c

smp_msg.o: ./smp_linux/smp_ipc/smp_msg.c ./smpcil.h \
		./smp_linux/smp_error/smp_error.h \
		./smp_linux/smp_ipc/smp_ipc.h
	$(CC) -c $(CFLAGS) -o smp_msg.o ./smp_linux/smp_ipc/smp_msg.c

smp_string.o: ./smp_linux/smp_string/smp_string.c ./smpcil.h \
		./smp_mpool/smp_mpool.h \
		./smp_linux/smp_error/smp_error.h \
		./smp_linux/smp_linux.h \
		./smp_linux/smp_string/smp_string.h
	$(CC) -c $(CFLAGS) -o smp_string.o ./smp_linux/smp_string/smp_string.c


smp_BoyerMoore.o: ./smp_linux/smp_string/smp_BoyerMoore.c ./smpcil.h \
		./smp_linux/smp_linux.h \
		./smp_mpool/smp_mpool.h \
		./smp_linux/smp_string/smp_string.h
	$(CC) -c $(CFLAGS) -o smp_BoyerMoore.o ./smp_linux/smp_string/smp_BoyerMoore.c

smp_list.o: ./smp_stl/smp_list/smp_list.c ./smpcil.h \
		./smp_linux/smp_error/smp_error.h \
		./smp_mpool/smp_mpool.h \
		./smp_stl/smp_list/smp_list.h
	$(CC) -c $(CFLAGS) -o smp_list.o ./smp_stl/smp_list/smp_list.c

smp_stack.o: ./smp_stl/smp_stack/smp_stack.c ./smpcil.h \
		./smp_mpool/smp_mpool.h \
		./smp_linux/smp_error/smp_error.h \
		./smp_stl/smp_stack/smp_stack.h
	$(CC) -c $(CFLAGS) -o smp_stack.o ./smp_stl/smp_stack/smp_stack.c

smp_array.o: ./smp_stl/smp_array/smp_array.c ./smpcil.h \
		./smp_mpool/smp_mpool.h \
		./smp_linux/smp_error/smp_error.h \
		./smp_stl/smp_array/smp_array.h
	$(CC) -c $(CFLAGS) -o smp_array.o ./smp_stl/smp_array/smp_array.c

smp_link.o: ./smp_stl/smp_link/smp_link.c ./smpcil.h \
		./smp_mpool/smp_mpool.h \
		./smp_linux/smp_linux.h \
		./smp_stl/smp_stl.h \
		./smp_stl/smp_link/smp_link.h
	$(CC) -c $(CFLAGS) -o smp_link.o ./smp_stl/smp_link/smp_link.c

smp_signal.o: ./smp_linux/smp_sig/smp_signal.c ./smpcil.h \
		./smp_linux/smp_error/smp_error.h \
		./smp_linux/smp_sig/smp_signal.h
	$(CC) -c $(CFLAGS) -o smp_signal.o ./smp_linux/smp_sig/smp_signal.c

smp_system.o: ./smp_linux/smp_system/smp_system.c ./smpcil.h \
		./smp_linux/smp_system/smp_system.h
	$(CC) -c $(CFLAGS) -o smp_system.o ./smp_linux/smp_system/smp_system.c

####### Install

install: 
	cp libsmpcil.so /usr/lib/
	bash install.sh
clean:
	rm -rf *.o
	rm -rf libsmpcil.so

uninstall:
	rm -rf /usr/include/smpcil
FORCE:

